### ISSUE TITLE
seven-sun-downs: main story

### ISSUE THREAD

**Issue by lramage94** [HexGearInc/seven-sun-downs#10]
So the difference is, the planet that we are on is actually earth in the future. In 2079, there was an experimental new ship designed with a new type of engine. This technology is similar to hyperspace like starwars

​ but in reality it actually accelerated through time.​ ​O​n it's first launch, it kno​cked Jupiter and Saturn out of alignment and they crashed into the sun​ creating a huge asteroid field​. This created chaos in our solar system​.​ I am still figuring out all the specifics, but basically, Earth is closer to the sun and it's not tilted on it's axis anymore but actually sideways. The moon goes vertically around and it's also closer. The rotation is also different. A day is now 168 hours long however,​ the moon still completes it's orbit in 24 hours. The side of the planet facing the sun is a burning wasteland but the other side is a raging jungle. It is dark when the moon isn't on the far side. There are lots of similar creatures to earth but they are different due to the new environment. And everything is accelerated. Things grow in hours. There are a few creatures that can survive the scorching side and they grow monstrously large. Things like giant crabs or other creatures with exoskeletons. The sea life is almost non existant as when the planet turns, all the water is vaporized but then when it turns back it rains down helping jungle grow. There are some underground rivers and streams that have some crazy fish/sea creatures. The "aliens" that we meet are actually humans that have adapted to the new environment. They live under ground because nothing can last on the surface longer than a "day" and they are either very black, because they venture closer to the surface, or super pale white because they live farther underground. They all have large ears like elves and they have very keen eye sight. But the paler they are, the more they dislike the sun as it is too bright. The dark ones explore the burning surface closest to the sun and they are very dark because of it. Aphrodite is one of the light skinned ones with a love of the jungle and our team captures her exploring. The black ones then attack our team because they are trying to get her back. The underground world is built with lots of technology. There are enormous cities that resemble Tokyo. It's very cyberpunk down there with lots of buildings and the technology is key to surviving. We have underground lakes, forests, and farther down there is even snow caverns. But not super deep because then the core makes it hot again. I am currently focusing on the environment and I am trying to have things automatically generated. I think for phase 1, we need to iron out our story and some background. I wanna have a loose plot line that sets the lore for our world. I am attaching a tabletop system that I am currently turning into an api. This will be the rpg engine. Then from there we can create lots of little quests and such. I want a basic story to introduce the team and characters but then I wanna have lots of room to grow. Think fantasy/Scifi version of skyrim but obviously not as big. Once we figure that part out, we can get a basic game together and then expand with graphics and things later.​

**Comment by crampage3** [comment]
Some sample game music for you. mostly theme type songs so they'd go during
cut scenes or endings and such. Let me know what you think!

**Comment by lramage94** [comment]
@crampage3 can you upload those to this ticket from the website? I don't see any attachments.

**Comment by crampage3** [comment]
It won't let me post any music file types. I'll send them form my pc this
time and see if they send properly.
